(ns e2.11 (:use clojure.test))
(defn make-interval [a b] [a b])
(def lower-bound first)
(def upper-bound second)
(defn sign-plus [x] (>= x 0))
(defn sign-minus [x] (< x 0))
(defn interval-signs [x ls us] (and (ls (lower-bound x)) (us (upper-bound x))))
(defn intervals-signs [x y xls xus yls yus] (and (interval-signs x xls xus) (interval-signs y yls yus)))
(defn mul-interval [x y]
  (cond
   (intervals-signs x y sign-plus sign-plus sign-plus sign-plus) (make-interval (* (lower-bound x) (lower-bound y)) (* (upper-bound x) (upper-bound y)))
   (intervals-signs x y sign-plus sign-plus sign-minus sign-plus) (make-interval (* (upper-bound x) (lower-bound y)) (* (upper-bound x) (upper-bound y)))
   (intervals-signs x y sign-plus sign-plus sign-minus sign-minus) (make-interval (* (upper-bound x) (lower-bound y)) (* (lower-bound x) (upper-bound y)))
   (intervals-signs x y sign-minus sign-plus sign-plus sign-plus) (make-interval (* (lower-bound x) (upper-bound y)) (* (upper-bound x) (upper-bound y)))
   (intervals-signs x y sign-minus sign-plus sign-minus sign-plus) (make-interval (min (* (lower-bound x) (upper-bound y)) (* (upper-bound x) (lower-bound y))) (max (* (lower-bound x) (lower-bound y)) (* (upper-bound x) (upper-bound y))))
   (intervals-signs x y sign-minus sign-plus sign-minus sign-minus) (make-interval (* (upper-bound x) (lower-bound y)) (* (lower-bound x) (lower-bound y)))
   (intervals-signs x y sign-minus sign-minus sign-plus sign-plus) (make-interval (* (lower-bound x) (upper-bound y)) (* (upper-bound x) (lower-bound y)))
   (intervals-signs x y sign-minus sign-minus sign-minus sign-plus) (make-interval (* (lower-bound x) (upper-bound y)) (* (lower-bound x) (lower-bound y)))
   (intervals-signs x y sign-minus sign-minus sign-minus sign-minus) (make-interval (* (upper-bound x) (upper-bound y)) (* (lower-bound x) (lower-bound y)))
   )
  )

(deftest plus-plus-plus-plus (is (= [21 32] (mul-interval [3 4] [7 8]))))
(deftest plus-plus-minus-plus (is (= [-28 32] (mul-interval [3 4] [-7 8]))))
(deftest plus-plus-minus-minus (is (= [-32 -21] (mul-interval [3 4] [-8 -7]))))
(deftest minus-plus-plus-plus (is (= [-24 32] (mul-interval [-3 4] [7 8]))))
(deftest minus-plus-minus-plus (is (= [-28 32] (mul-interval [-3 4] [-7 8]))) (is (= [-28 32] (mul-interval [-4 3] [-8 7]))))
(deftest minus-plus-minus-minus (is (= [-32 24] (mul-interval [-3 4] [-8 -7]))))
(deftest minus-minus-plus-plus (is (= [-32 -21] (mul-interval [-4 -3] [7 8]))))
(deftest minus-minus-minus-plus (is (= [-32 28] (mul-interval [-4 -3] [-7 8]))))
(deftest minus-minus-minus-minus (is (= [21 32] (mul-interval [-4 -3] [-8 -7]))))

(run-all-tests #"e2.11")
